<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Configurations>Debug;Release;Debug-Linux</Configurations>
    <AssemblyName>Superheater.$(MSBuildProjectName)</AssemblyName>
    <NoWarn>$(NoWarn);CA2007;CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IDisposableAnalyzers" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Minio" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tests.Core\Tests.Core.csproj" />
    <ProjectReference Include="..\Api.Client\Api.Client.csproj" />
    <ProjectReference Include="..\Common.Client\Common.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Tests.Core" />
  </ItemGroup>

</Project>
