// <auto-generated />
using System;
using Database.Client;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Client.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250517152305_AddSourcesTable")]
    partial class AddSourcesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Database.Client.DbEntities.CacheDbEntity", b =>
                {
                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Type");

                    b.ToTable("cache");
                });

            modelBuilder.Entity("Database.Client.DbEntities.HiddenTagsDbEntity", b =>
                {
                    b.Property<string>("Tag")
                        .HasColumnType("TEXT")
                        .HasColumnName("tag");

                    b.HasKey("Tag");

                    b.ToTable("hidden_tags");
                });

            modelBuilder.Entity("Database.Client.DbEntities.SettingsDbEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Name");

                    b.ToTable("settings");
                });

            modelBuilder.Entity("Database.Client.DbEntities.SourcesDbEntity", b =>
                {
                    b.Property<string>("Url")
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.HasKey("Url");

                    b.ToTable("sources");
                });

            modelBuilder.Entity("Database.Client.DbEntities.UpvotesDbEntity", b =>
                {
                    b.Property<Guid>("FixGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("fix_guid");

                    b.Property<bool>("IsUpvoted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_upvoted");

                    b.HasKey("FixGuid");

                    b.ToTable("upvotes");
                });
#pragma warning restore 612, 618
        }
    }
}
