// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Database.Client.Migrations;

[DbContext(typeof(DatabaseContext))]
partial class DatabaseContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

        modelBuilder.Entity("Common.Client.Config.DbEntities.HiddenTagsDbEntity", b =>
            {
                b.Property<string>("Tag")
                    .HasColumnType("TEXT")
                    .HasColumnName("tag");

                b.HasKey("Tag");

                b.ToTable("hidden_tags", "main");
            });

        modelBuilder.Entity("Common.Client.Config.DbEntities.SettingsDbEntity", b =>
            {
                b.Property<string>("Name")
                    .HasColumnType("TEXT")
                    .HasColumnName("name");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("value");

                b.HasKey("Name");

                b.ToTable("settings", "main");
            });

        modelBuilder.Entity("Common.Client.Config.DbEntities.UpvotesDbEntity", b =>
            {
                b.Property<Guid>("FixGuid")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT")
                    .HasColumnName("fix_guid");

                b.Property<bool>("IsUpvoted")
                    .HasColumnType("INTEGER")
                    .HasColumnName("is_upvoted");

                b.HasKey("FixGuid");

                b.ToTable("upvotes", "main");
            });
#pragma warning restore 612, 618
    }
}

