name: Build and test

on:
  push:

jobs:

  build-and-test-windows:

    runs-on: windows-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v7

    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Unit tests
      run: dotnet test --project ./src/Tests.Unit/Tests.Unit.csproj --no-build --verbosity normal

    - name: Unit tests (sequential)
      run: dotnet test --project ./src/Tests.Unit.Sequential/Tests.Unit.Sequential.csproj --no-build --verbosity normal
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-test-linux:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v7

    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Unit tests
      run: dotnet test --project ./src/Tests.Unit/Tests.Unit.csproj --no-build --verbosity normal

    - name: Unit tests (sequential)
      run: dotnet test --project ./src/Tests.Unit.Sequential/Tests.Unit.Sequential.csproj --no-build --verbosity normal
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
